### PR TITLE
New feature proposal - Link in header

### PR DESCRIPTION
**Pull request by iamarek**
Hey @alizahid ! Great plugin. It was missing one feature that I needed, so I figured I'll make a pull request and propose a little update to increase options.

Sometimes websites have landing pages for categories in the menu, and currently, there's no way of leading users to that page with the plugin.

I've added the possibility of switching header to be a link so that user can also navigate to the landing page of category.

It requires option `linkTitle` to be set to true, then checks if the link has attribute `href` and applies it to the header (changing `<header>` tag to `<a>` tag).

### CODE REVIEW

**Comment by alizahid** [comment]
Hey. Thanks for the PR! Can I see a demo?

**Comment by iamarek** [comment]
If you go to demo folder and set `linkTitle` to true in option, all headers will be clickable.

**Comment by iamarek** [comment]
You can also check it here:

https://slinky-demo.netlify.com/

Click on artists, and then on 'artists' in header.

image

**Comment by iamarek** [comment]
Hi @alizahid did you have time to review it by any chance?

**Pull request closed without merging**
